open_meteo:
  forecast_url: "https://api.open-meteo.com/v1/forecast"
  hourly_parameters_lst: ["temperature_2m","relative_humidity_2m","pressure_msl","surface_pressure","cloud_cover","wind_speed_10m","wind_speed_80m","wind_speed_120m",
    "wind_speed_180m","wind_direction_10m","wind_direction_80m","wind_direction_120m","wind_direction_180m","shortwave_radiation","direct_radiation","direct_normal_irradiance",
    "diffuse_radiation","precipitation","rain"]
    
gemats_db:
  iex_definitions_key_lst: ["MARKET AREA DEFINITION"]
  definition_geo_location_key_lst: ["RLDC","MARKET_AREA","COUNTRY"]
db_cred:
  host: 10.88.0.39
  port: 27017
  DEF_DB: DEFINITIONS
  IEX_DB: IEX
  user: gopi
  password: gopi2iex5
min_io:
  endpoint: http://10.88.0.39:9000
  access_key: miniorootadmin
  secret_key: m1n10@r00t@Psw
  source_bucket: ml-flow-trails
time_scale:
  url: "postgresql+psycopg2://greenko:greenko123@10.88.0.13:5433/data_ware_house"
  source_table: 'ap01_psp'
  sink_table: 'PSP_water_calculation'
  parameters_table: 'PSP_water_calc_parameters'
mail_cred:
  mail: donotreply@greenkogroup.com
  password: $ecur#iNf0Rep!yGr3#n
  host: 'smtp.office365.com'
  port: 587


